freebsd_instance:
  image: freebsd-11-2-release-amd64

freebsd_build_task:

  env:
    matrix:
      - node_js: "11"
        nodeArchive: "node-11.8.0"
        npmArchive: "npm-6.4.1_1"
      - node_js: "10"
        nodeArchive: "node10-10.15.1"
        npmArchive: "npm-node10-6.4.1_1"
      - node_js: "8"
        nodeArchive: "node8-8.15.0"
        npmArchive: "npm-node8-6.4.1_1"
      - node_js: "6"
        nodeArchive: "node6-6.16.0_1"
        npmArchive: "npm-node6-6.4.1_1"

  env:
    matrix:
      - abi: freebsd:11:x86:64
      - abi: freebsd:11:x86:32
        jailName: j11i386
        execPrefix: cbsd jexec jname=j11i386

  env:
    AUTH_TOKEN: ENCRYPTED[5e482f417304528148bb96eca8d030eacd6ab9972d482485fc4d42907283b995f658b351e0676e9493a37d815398f541]

  prepare_script:
    - |
      if test "$abi" = "freebsd:11:x86:32"; then
        ./scripts/configure_freebsd_ci_jail.sh $jailName $CIRRUS_WORKING_DIR;
        $execPrefix sed -i -- '' 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf; # use latest ports
        $execPrefix pkg update -f;
        $execPrefix pkg install -y python2 > /dev/null
      else
        sed -i '' 's/quarterly/latest/g' /etc/pkg/FreeBSD.conf; # use latest ports
      fi
    - $execPrefix pkg install -y c-ares gmake icu libnghttp2 libuv git > /dev/null
    - $execPrefix pkg add http://pkg.freebsd.org/$abi/latest/All/$nodeArchive.txz
    - $execPrefix pkg add http://pkg.freebsd.org/$abi/latest/All/$npmArchive.txz
    - $execPrefix node --version
    - $execPrefix npm --version
    - $execPrefix clang++ --version

  build_script:
    - |
      if test "$abi" = "freebsd:11:x86:32"; then
        changeDir="cd /etc/skel &&"
      fi
      echo "$changeDir npm install --unsafe-perm" | $execPrefix /bin/sh

  publish_script:
    - |
      if test "$CIRRUS_TAG" != ""; then
        curl -s -d '{"tag_name":"$CIRRUS_TAG"}' -H "$AUTH" https://api.github.com/repos/am11/node-sass/releases;
        pkg install -y bash > /dev/null
        for file in `ls vendor/**/*.node`; do
          parent=${file%/*};
          name=${parent##*/};
          fullyQualifiedName="$pwd/$parent/${name}_binding.node";
          mv "$file" "$parent/${name}_binding.node";
          echo -e "New filename\072 $fullyQualifiedName";
          ./scripts/upload-github-release-asset.sh github_api_token=$AUTH_TOKEN owner=am11 repo=node-sass tag=$CIRRUS_TAG filename=$fullyQualifiedName;
        done
      fi
